import React, { useEffect, useState } from 'react';import { fetchProducts, fetchCart, addToCart, removeCartItem, checkout } from './api';import ProductCard from './components/ProductCard';import Cart from './components/Cart';import ReceiptModal from './components/ReceiptModal';export default function App(){ const [products,setProducts]=useState([]); const [cart,setCart]=useState({items:[],total:0}); const [loading,setLoading]=useState(true); const [error,setError]=useState(null); const [showReceipt,setShowReceipt]=useState(false); const [receipt,setReceipt]=useState(null);
 async function refresh(){ setLoading(true); try{ const [ps,c]=await Promise.all([fetchProducts(), fetchCart()]); setProducts(ps); setCart(c);}catch(e){ setError(e.message)}finally{ setLoading(false)} }
 useEffect(()=>{ refresh(); const h=()=>refresh(); window.addEventListener('cart:refresh', h); return ()=>window.removeEventListener('cart:refresh', h) },[])
 const handleAdd=async(id)=>{ try{ await addToCart(id,1); await refresh() }catch(e){ alert(e.message) } }
 const handleRemove=async(id)=>{ try{ await removeCartItem(id); await refresh() }catch(e){ alert(e.message) } }
 const handleCheckout=async(name,email)=>{ try{ const rec=await checkout({ name, email }); setReceipt(rec.receipt); setShowReceipt(true); await refresh()}catch(e){ alert(e.message) } }
 if(loading) return <div className='container'><p>Loading…</p></div>
 if(error) return <div className='container'><p style={{color:'red'}}>{error}</p></div>
 return (<div className='container'><header className='header'><h1>Vibe Cart</h1><div className='cart-pill'><span>Cart: {cart.items.length} items</span><span>Total: ₹{cart.total.toFixed(2)}</span></div></header><main className='grid'>{products.map(p=> <ProductCard key={p.id} product={p} onAdd={()=>handleAdd(p.id)} />)}</main><section className='cart-section'><Cart items={cart.items} onRemove={handleRemove} /><CheckoutForm onCheckout={handleCheckout} /></section>{showReceipt && <ReceiptModal receipt={receipt} onClose={()=>setShowReceipt(false)} />}</div>) }
 function CheckoutForm({ onCheckout }){ const [name,setName]=useState(''); const [email,setEmail]=useState(''); return (<div className='checkout'><h3>Checkout</h3><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder='Jane Doe' /></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder='jane@example.com' /></label><button onClick={()=>onCheckout(name,email)} disabled={!name||!email}>Checkout</button></div>) }
